### ISSUE TITLE
Implement the register read/write command

### ISSUE THREAD

**Issue by pavel-kirienko** [UAVCAN/yakut#3]
Using the [standard register API](https://github.com/UAVCAN/public_regulated_data_types/blob/master/uavcan/register/384.Access.1.0.uavcan).

`yakut register 42` -- read all registers from node 42 and print them into stdout.

`yakut register 42 foo.bar` -- read register `foo.bar` and print its value.

`yakut register 42 foo.bar 123.456` -- write 123.456 into `foo.bar`. The command may need to send two service requests; the first one is needed to determine the type of the register so that the value can be converted into a representation expected by the server.

This issue is migrated from https://github.com/UAVCAN/pyuavcan/issues/56

**Comment by coderkalyan** [comment]
@pavel-kirienko I have an implementation almost ready that covers the requirements described above, and I will be able to open a pull request soon. You mentioned on the call that you have some of your own work that may conflict with this - could you please elaborate or link that work?

**Comment by pavel-kirienko** [comment]
Yes, but by "work" I mean a set of refined requirements. After some pondering, I want to suggest that we push back on this for now and focus on the more critical things.

**Comment by coderkalyan** [comment]
@pavel-kirienko Perhaps, but it just so happens that I am also blocked by this for some work at AmadorUAVs (not technically blocked because I can use `yakut call` but it's a pain). Also, I disagree that it isn't critical: yakut is the only working piece of tooling we have for V1 right now. Anything we can do to make it more complete will go a long way, especially considering the autoconfiguration system we had in mind for V1/UDRAL.

Also, I do have a 70% working implementation on my private fork (that may need to be refined given a new set of requirements). I would still like to get this finished if you don't mind - if you'd still rather not, I understand, I'll shelve it.

**Comment by pavel-kirienko** [comment]
Okay, let me document my thoughts on this here. This is more to start the discussion rather than to set any hard goals.

The main idea is to integrate this command with the [orchestration capability](https://pyuavcan.readthedocs.io/en/stable/pages/demo.html#orchestration) of Yukon. As you can see in the linked example, Yukon allows you to specify registers in orchestration files like this:

```yaml
PYTHONPATH: .yakut_compiled
uavcan:
  udp.iface: 127.9.0.0
  diagnostic:
    severity: 2
    timestamp: true
```

The above YAML is transformed into the following set of environment variables:

```bash
PYTHONPATH=".yakut_compiled"
UAVCAN__UDP__IFACE="127.9.0.0"
UAVCAN__DIAGNOSTIC__SEVERITY="2"
UAVCAN__DIAGNOSTIC__TIMESTAMP="1"
```

Which are then passed to the launched process. If the process is a locally executed node, the behavior is obvious. However, the node may also be executed remotely, e.g., on a dedicated hardware node like an airspeed sensor. We must unify the interface for both remote and local, hardware and software nodes, which implies that we need a proxy command that could absorb the environment variables given by the orchestrator and set them on the specified remote node.

Without this capability, launching a remote node from an orc-file would be unwieldy:

```yaml
uavcan:
  udp.iface: 127.9.0.0
  diagnostic:
    severity: 2

$=:
# Launch a local subscriber to receive data from an airspeed node (plus some other settings):
- $=: ./my_node
  uavcan:
    node.id: 42
    pub:
      heater_voltage.id:            2347
    sub.temperature_setpoint.id:    2345
    sub.temperature_measurement.id: 2346
    sub: &airspeed_service_foo
      differential_pressure.id:     1234
      static_air_temperature.id:    1235
  thermostat:
    pid.gains: [0.1, 0, 0]

# Launch the remote sensor node assuming it is configured with node-ID 43:
- $=:
  - y reg 43 uavcan.pub.differential_pressure.id 1234
  - y reg 43 uavcan.pub.static_air_temperature.id 1235
  - # Wait for the above commands to finish execution, then restart the node to apply new settings:
  - y call 43 uavcan.node.ExecuteCommand.1.1 "command: 65535"
```

See how we need to write multiple `y reg 43 <name> <value>`? We should search for a way to make the command ingest environment variables, but there is a problem: some of the environment variables are intended for the register command itself, e.g., `uavcan.udp.iface` defines how to reach the transport network. These should not be transferred to the remote node. One way to approach this is to make the set command accept a wildcard for register names and a special option/placeholder that tells it to look for the values in the environment variables, like this:

```
y reg 43 'uavcan.pub.*.id' --set
```

I am not sure, however, if this syntax with `--set` is entirely obvious. In the interest of user-friendliness we may want to sacrifice brevity by adding explicit subcommands `get`/`set` and requiring the name to be always provided in the form of a wildcard, like:

- `y reg get 42 '*'` -- read all registers from node 42 and print them into stdout.
- `y reg get 42 foo.bar foo.baz` -- read registers `foo.bar` and `foo.baz` and print their values as YAML.
- `y reg set 42 foo.bar=123.456 foo.baz='[123, 456]'` -- write 123.456 into `foo.bar` and [123, 456] into `foo.baz`.
- `y reg set 42 'foo.*' 'bar.*'` -- write registers named `foo.*` and `bar.*` taking values from the local environment variables.

Then, the last block in the above orc-file would be written like this instead:

```yaml
- $=: y reg set 43 'uavcan.pub.*' 'uavcan.sub.*'
  uavcan:
    node.id: 111 # This node-ID is used by the local proxy node (the reg command) to access the remote node.
    pub:  # This is the quasi-standard YAML merge syntax; find the anchor in the above example.
      <<: *airspeed_service_foo
```

You can see how Yakut Orchestrator handles this with `yakut -v orc test.yaml` or by adding `#!/usr/bin/env y -v orc` at the top of the file and then launching it as a script (the `-v` option will show the values of the environment variables passed to each launched process).
